const API_URL = "https://royaume-64-cases-api.teddysegura-ts.workers.dev";

const PIECES = {
  wK: "♔", wQ: "♕", wR: "♖", wB: "♗", wN: "♘", wP: "♙",
  bK: "♚", bQ: "♛", bR: "♜", bB: "♝", bN: "♞", bP: "♟"
};

const CHAPTERS = [
  { title:"L'échiquier abandonné", icon:"♟", story:"À peine arrivé dans le Royaume des 64 Cases, une porte gigantesque bloque le passage. Un Pion Blanc s'avance et te défie.", dialogue:"« Prouve que tu sais réfléchir. Trouve le coup décisif. »", puzzleTitle:"Mat en 1 coup", task:"Les Blancs jouent. Trouve le coup qui termine immédiatement la partie.", steps:1, position:{h6:"bK",g7:"wR",g2:"wK",e5:"wQ"} },
  { title:"Le Cavalier prisonnier", icon:"♞", story:"Dans une forêt sombre, un Cavalier Blanc est enfermé derrière des barreaux. La serrure ressemble à un petit échiquier.", dialogue:"« Libère-moi en trouvant mon bon saut. »", puzzleTitle:"Sacrifice", task:"Les Blancs jouent. Trouve le sacrifice décisif, puis le mat.", steps:2, position:{"g1":"wK","f1":"wR","e1":"wR","h2":"wP","g2":"wP","a2":"wP","e3":"wP","d4":"wP","c3":"wP","f7":"wQ","a3":"bQ","b7":"bP","b6":"bP","c5":"bP","d6":"bP","e8":"bR","e4":"bR","g7":"bP","h7":"bP","h8":"bK"} },
  { title:"Le Fou du pont", icon:"♝", story:"Un immense précipice coupe la route. Un Fou Noir garde le seul pont et refuse de te laisser passer.", dialogue:"« Montre-moi que tu maîtrises les diagonales. »", puzzleTitle:"Résolvez le problème", task:"Les Blancs jouent. Trouve le coup décisif.", steps:1, position:{"a1":"wR","b2":"wP","c2":"wQ","f2":"wP","g2":"wP","h2":"wP","g1":"wK","g8":"bK","h7":"bP","g7":"bP","f7":"bP","e5":"bR","d4":"bP","c4":"bP","c5":"bQ"} },
  { title:"La pièce oubliée", icon:"♜", story:"Deux Tours Noires gardent l'entrée du château. Une pièce oubliée peut pourtant changer le cours de la partie.", dialogue:"« Observe bien : une pièce bloquée peut encore se libérer. »", puzzleTitle:"Le fou décisif", task:"Trouve comment ton fou peut mater en un coup.", steps:1, position:{"f7":"wK","d4":"wB","h8":"bK","g7":"bP","h7":"bP"} },
  { title:"Le piège de la Reine", icon:"♛", story:"Dans le château, la Reine Blanche est encerclée. Elle explique qu'une victoire exige parfois d'accepter un sacrifice.", dialogue:"« La pièce la plus puissante n'est pas toujours celle qu'il faut conserver. »", puzzleTitle:"La menace invisible", task:"Les Blancs jouent. Trouve le coup qui révèle la menace décisive.", steps:1, position:{"g1":"wK","h4":"wQ","c2":"wB","e1":"wR","a2":"wP","b2":"wP","c3":"wP","f2":"wP","g2":"wP","h2":"wP","g8":"bK","f6":"bN","e8":"bR","a7":"bP","b7":"bP","c7":"bP","d5":"bP","f7":"bP","g7":"bP","h7":"bP"} },
  { title:"Le piège du Roi Noir", icon:"♚", story:"Le Roi Noir apparaît enfin. Il referme les portes derrière toi et pose une position sur l'échiquier.", dialogue:"« Deux coups. Pas un de plus. »", puzzleTitle:"Mat en deux coups", task:"Les Blancs jouent. Trouve comment mater en deux coups.", steps:2, position:{"c2":"wB","d6":"wK","c7":"wP","b4":"bP","c8":"bK"} },
  { title:"La salle des cases", icon:"♘", story:"Le sol entier devient un échiquier. Une trace lumineuse apparaît sous les sabots du Cavalier.", dialogue:"« Suis la trace en trois sauts sans quitter l'échiquier. »", puzzleTitle:"Mat en 2", task:"Les Blancs jouent. Trouve comment mater en deux coups.", steps:2, position:{"g1":"wK","f1":"wR","c7":"wR","b5":"wN","f4":"wQ","a3":"wP","b4":"wP","f3":"wP","g2":"wP","h2":"wP","b8":"bK","d8":"bR","h8":"bR","d3":"bN","d7":"bQ","e6":"bB","a7":"bP","b7":"bP","d5":"bP","f6":"bP","h7":"bP"} },
  { title:"L'armée noire", icon:"♞", story:"Sous le château, une armée entière attend. L'affronter de face serait impossible : il faut trouver la combinaison tactique.", dialogue:"« Un bon coup vaut parfois mieux qu'une armée. »", puzzleTitle:"Mat en 3", task:"Les Blancs jouent. Trouve comment mater en trois coups.", steps:3, position:{"h1":"wK","h2":"wP","g4":"wP","f6":"wP","c2":"wP","f3":"wR","e4":"wB","h6":"wQ","h8":"bK","g8":"bR","b8":"bR","e5":"bQ","h7":"bP","g6":"bP","f7":"bP","c4":"bP","a6":"bP"} },
  { title:"Le dernier duel", icon:"♚", story:"Au sommet du château, le Roi Noir t'attend seul devant son trône. Le duel final commence.", dialogue:"« Trois coups justes, et le royaume sera libre. »", puzzleTitle:"Le sacrifice royal", task:"Trouve la combinaison qui force le mat en trois coups.", steps:3, position:{"g1":"wK","a2":"wQ","a1":"wR","f1":"wR","c1":"wB","f7":"wN","b2":"wP","c2":"wP","d2":"wP","f2":"wP","g2":"wP","h2":"wP","g8":"bK","d8":"bQ","a8":"bR","f8":"bR","c8":"bB","b8":"bN","a7":"bP","b7":"bP","g7":"bP","h7":"bP"} }
];

const els={introCard:document.getElementById("introCard"),gameCard:document.getElementById("gameCard"),endingCard:document.getElementById("endingCard"),startBtn:document.getElementById("startBtn"),serverStatus:document.getElementById("serverStatus"),progressBar:document.getElementById("progressBar"),progressText:document.getElementById("progressText"),chapterNumber:document.getElementById("chapterNumber"),chapterTitle:document.getElementById("chapterTitle"),sceneIcon:document.getElementById("sceneIcon"),storyText:document.getElementById("storyText"),dialogueText:document.getElementById("dialogueText"),puzzleTitle:document.getElementById("puzzleTitle"),taskText:document.getElementById("taskText"),stepBadge:document.getElementById("stepBadge"),chessboard:document.getElementById("chessboard"),feedback:document.getElementById("feedback"),moveHint:document.getElementById("moveHint"),nextBtn:document.getElementById("nextBtn"),resetMoveBtn:document.getElementById("resetMoveBtn"),mysteryWord:document.getElementById("mysteryWord")};
let token=null,chapterIndex=0,stepIndex=0,selectedSquare=null,boardState={},puzzleComplete=false,gameComplete=false,busy=false;
function clonePosition(p){return JSON.parse(JSON.stringify(p))}function saveState(){sessionStorage.setItem("r64-session",JSON.stringify({token,chapterIndex,stepIndex,boardState,puzzleComplete,gameComplete}))}function clearState(){sessionStorage.removeItem("r64-session")}function renderProgress(){const done=gameComplete?9:chapterIndex;els.progressBar.style.width=`${Math.min(100,done/9*100)}%`;els.progressText.textContent=gameComplete?"9 chapitres terminés":`Chapitre ${chapterIndex+1} sur 9`}
function renderChapter(resetBoard=true){const c=CHAPTERS[chapterIndex];els.chapterNumber.textContent=`Chapitre ${chapterIndex+1}`;els.chapterTitle.textContent=c.title;els.sceneIcon.textContent=c.icon;els.storyText.textContent=c.story;els.dialogueText.textContent=c.dialogue;els.puzzleTitle.textContent=c.puzzleTitle;els.taskText.textContent=c.task;stepIndex=resetBoard?0:stepIndex;if(resetBoard)boardState=clonePosition(c.position);puzzleComplete=false;gameComplete=false;selectedSquare=null;els.feedback.textContent=c.task;els.feedback.className="feedback";els.nextBtn.classList.add("hidden");els.nextBtn.textContent="Continuer";updateStepBadge();renderBoard();renderProgress();saveState()}
function updateStepBadge(){const total=CHAPTERS[chapterIndex].steps;els.stepBadge.textContent=total===1?"1 coup à trouver":`Coup ${Math.min(stepIndex+1,total)} / ${total}`}
function squareColor(fileIndex,rank){return((fileIndex+rank)%2===0)?"dark":"light"}
function renderBoard(lastMove=null,wrongSquare=null){els.chessboard.innerHTML="";const files=["a","b","c","d","e","f","g","h"];for(let rank=8;rank>=1;rank--){files.forEach((file,fileIndex)=>{const sq=`${file}${rank}`,cell=document.createElement("button");cell.type="button";cell.className=`square ${squareColor(fileIndex,rank)}`;cell.dataset.square=sq;cell.setAttribute("role","gridcell");cell.setAttribute("aria-label",sq);if(selectedSquare===sq)cell.classList.add("selected");if(lastMove&&(lastMove.from===sq||lastMove.to===sq))cell.classList.add("last-move");if(wrongSquare===sq)cell.classList.add("wrong");if(boardState[sq]){const piece=document.createElement("span");piece.className="piece";piece.textContent=PIECES[boardState[sq]]+"\uFE0E";cell.appendChild(piece)}cell.addEventListener("pointerup",(event)=>{event.preventDefault();handleSquareClick(sq)},{passive:false});els.chessboard.appendChild(cell)})}}
function applyMove(uci){if(!uci||uci.length<4)return null;const from=uci.slice(0,2),to=uci.slice(2,4);if(boardState[from]){boardState[to]=boardState[from];delete boardState[from]}return{from,to}}
async function handleSquareClick(square){if(busy||puzzleComplete||gameComplete)return;if(!selectedSquare){if(!boardState[square]||!boardState[square].startsWith("w")){els.feedback.textContent="Choisis d'abord une pièce blanche.";els.feedback.className="feedback error";return}selectedSquare=square;renderBoard();return}if(selectedSquare===square){selectedSquare=null;renderBoard();return}const move=`${selectedSquare}${square}`,source=selectedSquare;selectedSquare=null;await submitMove(move,source,square)}
async function submitMove(move,from,to){busy=true;els.feedback.textContent="Vérification du coup…";els.feedback.className="feedback";try{const response=await fetch(`${API_URL}/move`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,move})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Erreur serveur");if(!data.correct){els.feedback.textContent=data.message||"Ce n'est pas le bon coup. Essaie encore.";els.feedback.className="feedback error";renderBoard(null,to||from);return}token=data.token;stepIndex=data.step||0;let lastMove=applyMove(move);if(data.opponentMove){renderBoard(lastMove);els.feedback.textContent="Bon coup ! Les Noirs répondent…";await new Promise(resolve=>setTimeout(resolve,650));lastMove=applyMove(data.opponentMove)||lastMove;}if(data.puzzleComplete){puzzleComplete=true;gameComplete=Boolean(data.gameComplete);els.feedback.textContent=gameComplete?"Dernière épreuve réussie ! Le royaume est libéré.":(["Échec et mat ! Le passage est ouvert.","Échec et mat ! Ton sacrifice a porté ses fruits.","Échec au roi noir ! Tu as trouvé le bon coup.","Échec et mat ! Ton fou et ton roi ont uni leurs forces."][chapterIndex]||"Épreuve réussie ! La route est ouverte.");els.feedback.className="feedback ok";els.nextBtn.textContent=gameComplete?"Révéler le mot mystère":"Chapitre suivant →";els.nextBtn.classList.remove("hidden")}else{els.feedback.textContent=data.message||`Bon coup ! Encore ${Math.max(1,CHAPTERS[chapterIndex].steps-stepIndex)} coup(s) à trouver.`;els.feedback.className="feedback ok"}updateStepBadge();renderBoard(lastMove);saveState()}catch(error){els.feedback.textContent="Validation indisponible. Réessaie dans un instant.";els.feedback.className="feedback error"}finally{busy=false}}
async function startGame(){busy=true;if(els.startBtn)els.startBtn.disabled=true;if(els.serverStatus)els.serverStatus.textContent="Ouverture des portes du royaume…";els.introCard.classList.add("hidden");els.gameCard.classList.remove("hidden");chapterIndex=0;stepIndex=0;clearState();renderChapter(true);try{const response=await fetch(`${API_URL}/start`,{method:"POST"}),data=await response.json();if(!response.ok||!data.token)throw new Error("start failed");token=data.token;saveState()}catch(error){els.feedback.textContent="Le plateau est prêt. Le serveur de validation n'est pas disponible pour le moment.";els.feedback.className="feedback error"}finally{busy=false;if(els.startBtn)els.startBtn.disabled=false}}
async function revealMystery(){busy=true;els.nextBtn.disabled=true;els.feedback.textContent="Le royaume révèle son dernier secret…";try{const response=await fetch(`${API_URL}/mystery`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}),data=await response.json();if(!response.ok||!data.word)throw new Error(data.error||"mystery failed");els.mysteryWord.textContent=data.word;els.gameCard.classList.add("hidden");els.endingCard.classList.remove("hidden");gameComplete=true;renderProgress();saveState()}catch(error){els.feedback.textContent="Impossible de révéler le mot pour le moment.";els.feedback.className="feedback error";els.nextBtn.disabled=false}finally{busy=false}}
function nextChapter(){if(busy||!puzzleComplete)return;if(gameComplete){revealMystery();return}chapterIndex+=1;if(chapterIndex>=CHAPTERS.length){revealMystery();return}renderChapter(true)}
if(els.startBtn)els.startBtn.addEventListener("click",startGame);els.nextBtn.addEventListener("click",nextChapter);els.resetMoveBtn.addEventListener("click",()=>{selectedSquare=null;els.feedback.textContent="Sélection annulée.";els.feedback.className="feedback";renderBoard()});
